In [1]:
import requests
import pandas as pd
import json
import time
import re

API_BASE = "https://hansard-api.parliament.uk"

HEADERS = {
    "User-Agent": (
        "KU-Leuven-semantic-change-research/1.0 "
        "(academic Master's thesis; "
        "contact: isaac.muscat@student.kuleuven.be)"
    ),
    "Accept": "application/json"
}

session = requests.Session()
session.headers.update(HEADERS)

TARGET_WORDS = [
    "war",
    "peace",
    "security"
]

In [2]:
url = f"{API_BASE}/overview/firstyear.json"

response = session.get(
    url,
    timeout=30
)

print("Status:", response.status_code)
print("URL:", response.url)
print("Content type:", response.headers.get("Content-Type"))

print("\nResponse:")
print(response.text[:2000])

response.raise_for_status()

Status: 200
URL: https://hansard-api.parliament.uk/overview/firstyear.json
Content type: application/json

Response:
1803

In [3]:
TEST_DATE = "1949-05-02"
TEST_HOUSE = "Commons"

url = (
    f"{API_BASE}/historicsittingdays/"
    f"{TEST_HOUSE}/{TEST_DATE}"
)

params = {
    "flattenStructure": True
}

response = session.get(
    url,
    params=params,
    timeout=30
)

print("Status:", response.status_code)
print("URL:", response.url)

if response.status_code != 200:
    print("\nResponse:")
    print(response.text[:5000])

response.raise_for_status()

historic_day = response.json()

print(
    json.dumps(
        historic_day,
        indent=2
    )[:15000]
)

Status: 200
URL: https://hansard-api.parliament.uk/historicsittingdays/Commons/1949-05-02?flattenStructure=True
{
  "Item": {
    "SittingDate": "1949-05-02T00:00:00",
    "House": "Commons",
    "SittingSections": [
      {
        "Name": "Commons Chamber",
        "ExternalId": "be3f5896-412f-4e4b-8aa0-b2a0f7a3c320",
        "DebateSections": [
          {
            "Title": "Commons Chamber",
            "ExternalId": "be3f5896-412f-4e4b-8aa0-b2a0f7a3c320",
            "ParentExternalId": null
          },
          {
            "Title": "Commons Chamber > House Of Commons",
            "ExternalId": "185d6cde-14fa-4815-9eeb-dbb91f24f3b0",
            "ParentExternalId": "be3f5896-412f-4e4b-8aa0-b2a0f7a3c320"
          },
          {
            "Title": "Commons Chamber > Prayers",
            "ExternalId": "45c2bf8a-915c-42f1-acde-0410ed6f426d",
            "ParentExternalId": "be3f5896-412f-4e4b-8aa0-b2a0f7a3c320"
          },
          {
            "Title": "Commons Chamber > Private Business",
            "ExternalId": "31a0129c-d36b-4c68-b3bb-54b2ed062755",
            "ParentExternalId": "be3f5896-412f-4e4b-8aa0-b2a0f7a3c320"
          },
          {
            "Title": "Commons Chamber > Private Business > West Bromwich Corporation Bill",
            "ExternalId": "886a5c9a-7590-46b8-a046-ef546896af8e",
            "ParentExternalId": "31a0129c-d36b-4c68-b3bb-54b2ed062755"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions",
            "ExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a",
            "ParentExternalId": "be3f5896-412f-4e4b-8aa0-b2a0f7a3c320"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Ministry Of Works",
            "ExternalId": "462b7ee7-8c55-44b1-bf60-d7b5f860e488",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Ministry Of Works > New Buildings (Government Leases)",
            "ExternalId": "400c1b82-c2e4-46ac-b0d5-1ae806901422",
            "ParentExternalId": "462b7ee7-8c55-44b1-bf60-d7b5f860e488"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Ministry Of Works > Factory, Feltham",
            "ExternalId": "72bd66d1-d6ce-44ea-a9bc-14c1c402c739",
            "ParentExternalId": "462b7ee7-8c55-44b1-bf60-d7b5f860e488"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Ministry Of Works > Hyde Park (Bathing)",
            "ExternalId": "8efc4eb0-a9ce-40f0-ac70-01f8399fad3a",
            "ParentExternalId": "462b7ee7-8c55-44b1-bf60-d7b5f860e488"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Ministry Of Works > Richmond Park",
            "ExternalId": "764556f5-7fac-430e-b8c1-1dcf0473c888",
            "ParentExternalId": "462b7ee7-8c55-44b1-bf60-d7b5f860e488"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Ministry Of Works > Requisitioned Premises, Bristol",
            "ExternalId": "e4a9b2bd-5c18-4d33-9d75-edd7839658bd",
            "ParentExternalId": "462b7ee7-8c55-44b1-bf60-d7b5f860e488"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Electricity Consultative Councils",
            "ExternalId": "6e0e7afe-9c1e-459c-bc9c-e9eb911582e8",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Coal Industry",
            "ExternalId": "d6e82e9a-0b92-46cd-bac4-f914713d02fd",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Coal Industry > Opencast Mining, Tankersley",
            "ExternalId": "fc988ef7-75cc-4e27-88d3-90819979c189",
            "ParentExternalId": "d6e82e9a-0b92-46cd-bac4-f914713d02fd"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Coal Industry > Scottish Coalfield (Developments)",
            "ExternalId": "118ecbc5-1ee2-4d83-b569-c7bf2546bff7",
            "ParentExternalId": "d6e82e9a-0b92-46cd-bac4-f914713d02fd"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Leasehold Committee (Report)",
            "ExternalId": "b49dffc2-4626-4e8c-a979-68f330ae4cb3",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Food Supplies",
            "ExternalId": "a6961b0d-8ca0-474b-a23c-e1656f377db6",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Food Supplies > Maize",
            "ExternalId": "4316d75e-a587-4255-ad14-ffa18c987ccb",
            "ParentExternalId": "a6961b0d-8ca0-474b-a23c-e1656f377db6"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Food Supplies > Fish Friers (Fats Allocation)",
            "ExternalId": "da920b49-342a-4a81-839e-a7476ce5b435",
            "ParentExternalId": "a6961b0d-8ca0-474b-a23c-e1656f377db6"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Food Supplies > Retail Licence (Sweets)",
            "ExternalId": "c452ed59-5e75-4508-8ce7-6a2999ab8495",
            "ParentExternalId": "a6961b0d-8ca0-474b-a23c-e1656f377db6"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Food Supplies > Algerian Wine",
            "ExternalId": "37e38967-487b-4809-8850-cfbe4ee06a19",
            "ParentExternalId": "a6961b0d-8ca0-474b-a23c-e1656f377db6"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Food Supplies > Enforcement Inspectors (Visits)",
            "ExternalId": "636f660b-82aa-4316-a584-c0def39a7b23",
            "ParentExternalId": "a6961b0d-8ca0-474b-a23c-e1656f377db6"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Food Supplies > Agricultural Workers (Meat)",
            "ExternalId": "2a6bd615-bda0-4b34-bb01-06de95f7158b",
            "ParentExternalId": "a6961b0d-8ca0-474b-a23c-e1656f377db6"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Food Supplies > Retail Prices",
            "ExternalId": "ab7366e7-91a3-43c0-845c-b2bdea04e233",
            "ParentExternalId": "a6961b0d-8ca0-474b-a23c-e1656f377db6"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Food Supplies > Potatoes",
            "ExternalId": "30c16817-eb23-4127-9b5a-bd6d1fb07122",
            "ParentExternalId": "a6961b0d-8ca0-474b-a23c-e1656f377db6"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Transport",
            "ExternalId": "24b3c92a-78ce-4f64-9c53-7594a2d899a6",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Transport > Forth And Clyde Canal",
            "ExternalId": "1158ca56-2863-48fa-8498-082f7800d3fa",
            "ParentExternalId": "24b3c92a-78ce-4f64-9c53-7594a2d899a6"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Transport > Riccarton, Roxburgh",
            "ExternalId": "d8b61064-8e39-4d47-990e-8d47ab8a5388",
            "ParentExternalId": "24b3c92a-78ce-4f64-9c53-7594a2d899a6"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Transport > C Licence Vehicles",
            "ExternalId": "186bed7b-0542-498e-a8ab-cd9a15e5b601",
            "ParentExternalId": "24b3c92a-78ce-4f64-9c53-7594a2d899a6"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Transport > Road Safety (Grants)",
            "ExternalId": "31eb9292-b849-43ca-bdb2-2eebcc8979af",
            "ParentExternalId": "24b3c92a-78ce-4f64-9c53-7594a2d899a6"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Transport > Rspa (Expenditure)",
            "ExternalId": "9cd2927a-b6e2-4a5c-bbf5-08efb44c9796",
            "ParentExternalId": "24b3c92a-78ce-4f64-9c53-7594a2d899a6"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Transport > Buses (Standing Passengers)",
            "ExternalId": "27ee7272-7b14-419d-ab5a-ef6dada15b3a",
            "ParentExternalId": "24b3c92a-78ce-4f64-9c53-7594a2d899a6"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Transport > Users' Consultative Committee, London",
            "ExternalId": "9f567be3-85b3-47d8-b775-cd612a9bb2d7",
            "ParentExternalId": "24b3c92a-78ce-4f64-9c53-7594a2d899a6"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Transport > Railway Bridges (Road Surfaces)",
            "ExternalId": "a1747495-b2ab-4ea9-97a5-1aec9b79b373",
            "ParentExternalId": "24b3c92a-78ce-4f64-9c53-7594a2d899a6"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Armed Forces (Recruiting Appeals)",
            "ExternalId": "40fa7ccb-8685-4cc6-868d-af61238131ea",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Ministers And Officials (Salaries)",
            "ExternalId": "24f4c06d-580c-423b-8036-41c7b2403349",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Hm Ships, China (Air Support)",
            "ExternalId": "927d38e9-82a9-4ee4-be95-e2b0235120d1",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > British Commonwealth And Empire",
            "ExternalId": "5abbbfe0-9c96-448e-b969-2955d40dafd5",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > British Commonwealth And Empire > Official Designation",
            "ExternalId": "420cc30a-d4d6-426f-bdd9-fc5abf318660",
            "ParentExternalId": "5abbbfe0-9c96-448e-b969-2955d40dafd5"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > British Commonwealth And Empire > Commemoration Date",
            "ExternalId": "d0707a71-675b-475c-969b-a6fe21c28fe7",
            "ParentExternalId": "5abbbfe0-9c96-448e-b969-2955d40dafd5"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Personal Incomes, Costs And Prices",
            "ExternalId": "c0831c1a-2edd-47cc-906c-eae16f58883a",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Queen's Hall (Rebuilding)",
            "ExternalId": "7358af47-0f8f-48a1-bde8-8885d9487f78",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Foreign Office (Registry Clerk)",
            "ExternalId": "0a448a57-cb00-4a02-a197-cec21d682b4a",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Germany",
            "ExternalId": "f7751be8-f495-4975-ad45-b2bd810b6dca",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Germany > Western Frontier Adjustments",
            "ExternalId": "0a08e17c-1713-4075-b737-c1c66000b69e",
            "ParentExternalId": "f7751be8-f495-4975-ad45-b2bd810b6dca"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Germany > Unemployment",
            "ExternalId": "3ec02cb9-4468-4ecb-8168-b48001966bb7",
            "ParentExternalId": "f7751be8-f495-4975-ad45-b2bd810b6dca"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Spain (Government Policy)",
            "ExternalId": "95a7727c-440a-4cfe-bfbf-0499e29f6aed",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Austria (Association Of Independents)",
            "ExternalId": "3a3bfb3e-31ff-4856-8b6f-42ff3d35889a",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Ussr",
            "ExternalId": "b8664a50-652e-4c5a-98e9-c0bbcc761773",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Ussr > Service Attach\u00e9s, Moscow",
            "ExternalId": "bc8a62e1-3888-49bc-a374-a3828712bee7",
            "ParentExternalId": "b8664a50-652e-4c5a-98e9-c0bbcc761773"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Ussr > \"British Ally\" (Mr A P Johnstone)",
            "ExternalId": "79a1694b-7ce4-4d6d-af0e-8530f2d5de19",
            "ParentExternalId": "b8664a50-652e-4c5a-98e9-c0bbcc761773"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Bomber Aircraft (Prices)",
            "ExternalId": "7e30b6f6-f58d-49bb-9919-692734dfcb62",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Oral Answers To Questions > Catering Wages Act (Orders)",
            "ExternalId": "8a95f312-5f95-4c0f-a7f8-906fa6089d9e",
            "ParentExternalId": "2e4e7da3-f7cf-488a-be8d-36c31a0fcc9a"
          },
          {
            "Title": "Commons Chamber > Orders Of The Day",
            "ExternalId": "e185977e-6c98-4084-bc1c-5c59fc6abbf9",
            "ParentExternalId": "be3f5896-412f-4e4b-8aa0-b2a0f7a3c320"
          },
          {
            "Title": "Commons Chamber > Orders Of The Day > Iron And Steel Bill",
            "ExternalId": "3f20589b-b12f-44dd-b841-0e8c1f5bccd2",
            "ParentExternalId": "e185977e-6c98-4084-bc1c-5c59fc6abbf9"
          },
          {
            "Title": "Commons Chamber > Clause 20\u2014(Power To Acquire Securi- Ties Of Certain Additional Com- Panies)",
            "ExternalId": "c74f42e9-b646-4487-ba6a-e5d04be7ec5c",
            "ParentExternalId": "be3f58

In [4]:
def inspect_json(
    obj,
    depth=0,
    max_depth=5
):
    indent = "    " * depth

    if depth > max_depth:
        return

    if isinstance(obj, dict):

        for key, value in obj.items():

            print(
                f"{indent}{key}: "
                f"{type(value).__name__}"
            )

            if isinstance(
                value,
                (dict, list)
            ):
                inspect_json(
                    value,
                    depth + 1,
                    max_depth
                )

    elif isinstance(obj, list):

        print(
            f"{indent}[{len(obj)} items]"
        )

        if obj:
            inspect_json(
                obj[0],
                depth + 1,
                max_depth
            )


if "historic_day" in globals():
    inspect_json(historic_day)
else:
    print(
        "historic_day has not been loaded yet. "
        "Run the previous cell successfully first."
    )

Item: dict
    SittingDate: str
    House: str
    SittingSections: list
        [2 items]
            Name: str
            ExternalId: str
            DebateSections: list
                [65 items]
                    Title: str
                    ExternalId: str
                    ParentExternalId: NoneType
Success: bool
Errors: list
    [0 items]

In [5]:
TEST_START = "1945-01-01"
TEST_END   = "1950-12-31"


def search_spoken_contributions(
    term,
    start_date,
    end_date,
    house="Commons",
    skip=0,
    take=100,
    max_retries=3
):
    url = f"{API_BASE}/search/contributions/Spoken.json"

    params = {
        "queryParameters.house": house,
        "queryParameters.startDate": start_date,
        "queryParameters.endDate": end_date,
        "queryParameters.searchTerm": term,
        "queryParameters.skip": skip,
        "queryParameters.take": take
    }

    for attempt in range(max_retries):

        try:
            response = session.get(
                url,
                params=params,
                timeout=60
            )

            if response.status_code == 200:
                return response.json()

            print(
                f"{term} {start_date} to {end_date}: "
                f"HTTP {response.status_code}"
            )

            print(response.text[:300])

        except requests.RequestException as e:
            print(
                f"Request error "
                f"({attempt + 1}/{max_retries}):",
                e
            )

        time.sleep(2 ** attempt)

    return None

test_searches = {}

for word in TARGET_WORDS:

    test_searches[word] = (
        search_spoken_contributions(
            term=word,
            start_date=TEST_START,
            end_date=TEST_END,
            house="Commons",
            take=100
        )
    )

    time.sleep(1)

In [6]:
"""EUROPE_TERMS = [
    "Albania",
    "Armenia",
    "Austria",
    "Andorra",
    "Azerbaijan",
    "Belarus",
    "Belgium",
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Denmark",
    "Czech Republic",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Georgia",
    "Hungary",
    "Ireland",
    "Italy",
    "Iceland",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Liechtenstein",
    "Malta",
    "Moldova",
    "Monaco",
    "Montenegro",
    "Netherlands",
    "Norway",
    "Macedonia",
    "Poland",
    "Portugal",
    "Russia",
    "Soviet Union",
    "Romania",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Sweden",
    "Switzerland",
    "Spain",
    "San Marino",
    "Turkey",
    "Ukraine",
    "Yugoslavia"
]"""

EUROPE_TERMS = [
    "British Empire",
    "Empire",
    "Commonwealth",
    "Dominion",
    "Dominions",
    "Colony",
    "Colonies"
]

In [7]:
def get_term_count(
    term,
    start_date="1900-01-01",
    end_date="2000-12-31",
    house="Commons"
):
    result = search_spoken_contributions(
        term=term,
        start_date=start_date,
        end_date=end_date,
        house=house,
        take=1
    )

    if result is None:
        return None

    return result.get(
        "TotalResultCount"
    )


count_rows = []

for group_name, terms in [
    ("Europe / EU", EUROPE_TERMS),
]:

    for term in terms:

        for house in [
            "Commons",
            "Lords"
        ]:

            print(
                f"Searching: {term} / {house}"
            )

            count = get_term_count(
                term=term,
                house=house
            )

            count_rows.append({
                "group":
                    group_name,
                "term":
                    term,
                "house":
                    house,
                "count":
                    count
            })

            time.sleep(0.5)


term_counts = pd.DataFrame(
    count_rows
)

display(term_counts)

Searching: British Empire / Commons
Searching: British Empire / Lords
Searching: Empire / Commons
Searching: Empire / Lords
Searching: Commonwealth / Commons
Searching: Commonwealth / Lords
Searching: Dominion / Commons
Searching: Dominion / Lords
Searching: Dominions / Commons
Searching: Dominions / Lords
Searching: Colony / Commons
Searching: Colony / Lords
Searching: Colonies / Commons
Searching: Colonies / Lords

          group            term    house  count
0   Europe / EU  British Empire  Commons  15886
1   Europe / EU  British Empire    Lords   5034
2   Europe / EU          Empire  Commons  29819
3   Europe / EU          Empire    Lords   8815
4   Europe / EU    Commonwealth  Commons  48037
5   Europe / EU    Commonwealth    Lords  17386
6   Europe / EU        Dominion  Commons   9458
7   Europe / EU        Dominion    Lords   2123
8   Europe / EU       Dominions  Commons  14283
9   Europe / EU       Dominions    Lords   4340
10  Europe / EU          Colony  Commons   9633
11  Europe / EU          Colony    Lords   2676
12  Europe / EU        Colonies  Commons  35933
13  Europe / EU        Colonies    Lords   5814

In [9]:
FIVE_YEAR_TERMS = [
    "Empire",
    "Commonwealth"
]

five_year_rows = []

for start_year in range(1900, 2001, 5):
    end_year = min(start_year + 4, 2000)

    start_date = f"{start_year}-01-01"
    end_date = f"{end_year}-12-31"
    period = f"{start_year}-{end_year}"

    for term in FIVE_YEAR_TERMS:

        print(f"Searching: {term} / {period}")

        count = get_term_count(
            term=term,
            start_date=start_date,
            end_date=end_date,
            house="Commons"
        )

        five_year_rows.append({
            "period": period,
            "term": term,
            "count": count
        })

        time.sleep(0.5)

five_year_counts = pd.DataFrame(five_year_rows)

five_year_counts_wide = (
    five_year_counts
    .pivot(
        index="period",
        columns="term",
        values="count"
    )
    .reset_index()
)

display(five_year_counts_wide)

Searching: Empire / 1900-1904
Searching: Commonwealth / 1900-1904
Commonwealth 1900-01-01 to 1904-12-31: HTTP 500
{"Message":"An error has occurred."}
Searching: Empire / 1905-1909
Searching: Commonwealth / 1905-1909
Searching: Empire / 1910-1914
Searching: Commonwealth / 1910-1914
Searching: Empire / 1915-1919
Searching: Commonwealth / 1915-1919
Searching: Empire / 1920-1924
Searching: Commonwealth / 1920-1924
Searching: Empire / 1925-1929
Searching: Commonwealth / 1925-1929
Searching: Empire / 1930-1934
Searching: Commonwealth / 1930-1934
Searching: Empire / 1935-1939
Searching: Commonwealth / 1935-1939
Searching: Empire / 1940-1944
Searching: Commonwealth / 1940-1944
Searching: Empire / 1945-1949
Searching: Commonwealth / 1945-1949
Searching: Empire / 1950-1954
Searching: Commonwealth / 1950-1954
Searching: Empire / 1955-1959
Searching: Commonwealth / 1955-1959
Searching: Empire / 1960-1964
Searching: Commonwealth / 1960-1964
Searching: Empire / 1965-1969
Searching: Commonwealth / 1965-1969
Searching: Empire / 1970-1974
Searching: Commonwealth / 1970-1974
Searching: Empire / 1975-1979
Searching: Commonwealth / 1975-1979
Searching: Empire / 1980-1984
Searching: Commonwealth / 1980-1984
Searching: Empire / 1985-1989
Searching: Commonwealth / 1985-1989
Searching: Empire / 1990-1994
Searching: Commonwealth / 1990-1994
Searching: Empire / 1995-1999
Searching: Commonwealth / 1995-1999
Searching: Empire / 2000-2000
Searching: Commonwealth / 2000-2000

term     period  Commonwealth  Empire
0     1900-1904           NaN  1706.0
1     1905-1909         152.0  1043.0
2     1910-1914         270.0  2121.0
3     1915-1919         150.0  1808.0
4     1920-1924         167.0  1885.0
5     1925-1929         280.0  2771.0
6     1930-1934         647.0  4572.0
7     1935-1939         591.0  3808.0
8     1940-1944         697.0  2223.0
9     1945-1949        2042.0  2344.0
10    1950-1954        3954.0  1698.0
11    1955-1959        4945.0   833.0
12    1960-1964        8032.0   513.0
13    1965-1969        6973.0   392.0
14    1970-1974        5417.0   342.0
15    1975-1979        3316.0   396.0
16    1980-1984        2662.0   334.0
17    1985-1989        2729.0   320.0
18    1990-1994        2209.0   368.0
19    1995-1999        2021.0   280.0
20    2000-2000         594.0    62.0

In [17]:
term_counts_wide = (
    term_counts
    .pivot(
        index=[
            "group",
            "term"
        ],
        columns="house",
        values="count"
    )
    .reset_index()
)

if (
    "Commons" in term_counts_wide.columns
    and
    "Lords" in term_counts_wide.columns
):
    term_counts_wide[
        "Total"
    ] = (
        term_counts_wide["Commons"]
        .fillna(0)
        +
        term_counts_wide["Lords"]
        .fillna(0)
    )

term_counts_wide = (
    term_counts_wide
    .sort_values(
        [
            "group",
            "Total"
        ],
        ascending=[
            True,
            False
        ]
    )
)

display(
    term_counts_wide
)

house        group                     term  Commons  Lords  Total
4      Europe / EU             Commonwealth    48037  17386  65423
2      Europe / EU                 Colonies    35933   5814  41747
8      Europe / EU                   Empire    29819   8815  38634
0      Europe / EU     British Commonwealth    15967   7408  23375
1      Europe / EU           British Empire    15886   5034  20920
7      Europe / EU                Dominions    14283   4340  18623
3      Europe / EU                   Colony     9633   2676  12309
6      Europe / EU                 Dominion     9458   2123  11581
5      Europe / EU  Commonwealth of Nations     7753   3782  11535

In [38]:
for word, data in test_searches.items():

    print("\n" + "=" * 70)
    print(word.upper())
    print("=" * 70)

    print(
        "Python type:",
        type(data).__name__
    )

    if isinstance(data, dict):

        print(
            "Top-level keys:",
            list(data.keys())
        )

        for key, value in data.items():

            if isinstance(value, list):
                print(
                    f"{key}: list with "
                    f"{len(value):,} items"
                )

            elif not isinstance(
                value,
                (dict, list)
            ):
                print(
                    f"{key}: {value}"
                )

    print("\nPreview:")
    print(
        json.dumps(
            data,
            indent=2
        )[:5000]
    )

======================================================================
WAR
======================================================================
Python type: dict
Top-level keys: ['SearchTerms', 'SpokenResultCount', 'WrittenResultCount', 'CorrectionsResultCount', 'DivisionsResultCount', 'Results', 'TotalResultCount']
SearchTerms: list with 1 items
SpokenResultCount: 0
WrittenResultCount: 0
CorrectionsResultCount: 0
DivisionsResultCount: 0
Results: list with 100 items
TotalResultCount: 30334

Preview:
{
  "SearchTerms": [
    "war"
  ],
  "SpokenResultCount": 0,
  "WrittenResultCount": 0,
  "CorrectionsResultCount": 0,
  "DivisionsResultCount": 0,
  "Results": [
    {
      "MemberName": "",
      "MemberId": -1,
      "AttributedTo": "Sir G. Jeffreys",
      "ItemId": 9080427,
      "ContributionExtId": "c95fec24-1a1d-466c-8474-bb8e0f7421ac",
      "ContributionText": "The best way to preserve peace is to be prepared for war.",
      "ContributionTextFull": "The best way to preserve peace is to be prepared for war.",
      "HRSTag": null,
      "HansardSection": null,
      "Timecode": null,
      "DebateSection": "Oil Refinery, The Solent",
      "DebateSectionId": 3069976,
      "DebateSectionExtId": "c0636361-82cc-45fd-8cb1-3100ab4cd8be",
      "SittingDate": "1950-12-15T00:00:00",
      "Section": "Commons Chamber",
      "House": "Commons",
      "OrderInDebateSection": 40,
      "DebateSectionOrder": 10,
      "Rank": 96
    },
    {
      "MemberName": "",
      "MemberId": -1,
      "AttributedTo": "Mr. Grimond  (Orkney and Shetland)",
      "ItemId": 9080077,
      "ContributionExtId": "4740ad57-084e-4eaa-8b5d-8c82973c37ea",
      "ContributionText": "Among the many phrases which have been doing double. or even triple, duty lately there is one very well known in modern politics\u2014\"over-all planning.\" I think that it is very often used rather vaguely, but if there was an occasion for over-all planning, ",
      "ContributionTextFull": "Among the many phrases which have been doing double. or even triple, duty lately there is one very well known in modern politics\u2014\"over-all planning.\" I think that it is very often used rather vaguely, but if there was an occasion for over-all planning, this is surely it. The answer to the hon. Member for Lady- <span id=\"1489\" class=\"column-number\" data-column-number=\"1489\"></span> wood (Mr. Yates) is that what are now required are not so much detailed controls, but an over-all international plan for the production and allocation of vital raw materials.<p></p> Now, this situation arises from the present state of the world. Yesterday we had a debate on that situation. Some of us, myself included, do not feel that we should consider ourselves in a state of war with Russia. Many of us do not feel that rearmament alone will guarantee peace. But whatever our views on foreign affairs, we must realise, as a Member of the United Nations, that at the moment we are at war in Korea and in China, and the whole situation we are debating today flows from the fact of war or the threat of war. Those of us who may disagree on foreign policy can be agreed on the very great urgency of ensuring for this country adequate materials for rearmament, and ensuring that those materials are guaranteed to us before they become available to potential aggressors. I say this without in the least abandoning the position that we should make every possible effort to maintain peace.<p></p> My own feeling is that the most vital materials we are concerned with today are comparatively small in number\u2014those that contribute directly to rearmament. I think they are generally considered to be certain materials used for the hardening of steel, rubber, oil and, nowadays, atomic substances. It is on those materials especially, that I intend to address a few remarks to the House. In doing so, I am by no means under-estimating the seriousness of the effects of those matters to which the hon. Member for Ladywood, the hon. Member for Solihull (Mr. M. Lindsay) and the hon. Member for Aylesbury (Mr. Summers) have drawn attention, but it is these particular metals and other substances, to which I want to draw attention.<p></p> With our Commonwealth and the United States of America we control a very large proportion of these supplies, and in the past we have had considerable experience in dealing with these metals and these substances in a war situation. I hope we shall not repeat the mistakes, but will have learned the lessons of the situation which existed before the last war. It is common knowledge, I think, that at that time we went on supplying Germany <span id=\"1490\" class=\"column-number\" data-column-number=\"1490\"></span> with certain metals which were vital to her rearmament far beyond the time when it was obvious that it was dangerous to do so.<p></p> We must follow up what the Prime Minister said yesterday and ask what machinery is now being established to ensure that those countries which are or are likely to be aggressors, are rationed in their supplies of these materials. It was possible to ration their materials during the war, and the system could have been put into operation before the war. I think that we have a perfect right to introduce machinery which will guarantee that we, with our Allies and the other Members of the, United Nations who are co-operating with us, have the first call upon these materials. A rationing system should be introduced to guarantee only reasonab

======================================================================
PEACE
======================================================================
Python type: dict
Top-level keys: ['SearchTerms', 'SpokenResultCount', 'WrittenResultCount', 'CorrectionsResultCount', 'DivisionsResultCount', 'Results', 'TotalResultCount']
SearchTerms: list with 1 items
SpokenResultCount: 0
WrittenResultCount: 0
CorrectionsResultCount: 0
DivisionsResultCount: 0
Results: list with 100 items
TotalResultCount: 5000

Preview:
{
  "SearchTerms": [
    "peace"
  ],
  "SpokenResultCount": 0,
  "WrittenResultCount": 0,
  "CorrectionsResultCount": 0,
  "DivisionsResultCount": 0,
  "Results": [
    {
      "MemberName": "",
      "MemberId": -1,
      "AttributedTo": "Sir G. Jeffreys",
      "ItemId": 9080427,
      "ContributionExtId": "c95fec24-1a1d-466c-8474-bb8e0f7421ac",
      "ContributionText": "The best way to preserve peace is to be prepared for war.",
      "ContributionTextFull": "The best way to preserve peace is to be prepared for war.",
      "HRSTag": null,
      "HansardSection": null,
      "Timecode": null,
      "DebateSection": "Oil Refinery, The Solent",
      "DebateSectionId": 3069976,
      "DebateSectionExtId": "c0636361-82cc-45fd-8cb1-3100ab4cd8be",
      "SittingDate": "1950-12-15T00:00:00",
      "Section": "Commons Chamber",
      "House": "Commons",
      "OrderInDebateSection": 40,
      "DebateSectionOrder": 10,
      "Rank": 128
    },
    {
      "MemberName": "",
      "MemberId": -1,
      "AttributedTo": "Mr. Lindgren",
      "ItemId": 9080429,
      "ContributionExtId": "1f06d899-090b-4d5a-9602-15a6025af9a7",
      "ContributionText": "I am not arguing on that basis, but if war comes to this country\u2014I shall deal with the defence aspect later\u2014a totally different situation will arise. But we must organise the economy of this country and the lives of its people on the basis of peace. I s",
      "ContributionTextFull": "I am not arguing on that basis, but if war comes to this country\u2014I shall deal with the defence aspect later\u2014a totally different situation will arise. But we must organise the economy of this country and the lives of its people on the basis of peace. I should have thought that it would have been generally recognised that the function of Government is to enable people to live at as high a standard of life as possible, at peace with another, in their own country.",
      "HRSTag": null,
      "HansardSection": null,
      "Timecode": null,
      "DebateSection": "Oil Refinery, The Solent",
      "DebateSectionId": 3069976,
      "DebateSectionExtId": "c0636361-82cc-45fd-8cb1-3100ab4cd8be",
      "SittingDate": "1950-12-15T00:00:00",
      "Section": "Commons Chamber",
      "House": "Commons",
      "OrderInDebateSection": 42,
      "DebateSectionOrder": 10,
      "Rank": 85
    },
    {
      "MemberName": "",
      "MemberId": -1,
      "AttributedTo": "Mr. Lindgren",
      "ItemId": 9080426,
      "ContributionExtId": "a1a8bd59-6f13-4ac3-81d7-5aee8472547e",
      "ContributionText": "The hon. and gallant Gentleman must remember that we live for peace and not for war.",
      "ContributionTextFull": "The hon. and gallant Gentleman must remember that we live for peace and not for war.",
      "HRSTag": null,
      "HansardSection": null,
      "Timecode": null,
      "DebateSection": "Oil Refinery, The Solent",
      "DebateSectionId": 3069976,
      "DebateSectionExtId": "c0636361-82cc-45fd-8cb1-3100ab4cd8be",
      "SittingDate": "1950-12-15T00:00:00",
      "Section": "Commons Chamber",
      "House": "Commons",
      "OrderInDebateSection": 38,
      "DebateSectionOrder": 10,
      "Rank": 64
    },
    {
      "MemberName": "",
      "MemberId": -1,
      "AttributedTo": "Mr. Grimond  (Orkney and Shetland)",
      "ItemId": 9080077,
      "ContributionExtId": "4740ad57-084e-4eaa-8b5d-8c82973c37ea",
      "ContributionText": "Among the many phrases which have been doing double. or even triple, duty lately there is one very well known in modern politics\u2014\"over-all planning.\" I think that it is very often used rather vaguely, but if there was an occasion for over-all planning, ",
      "ContributionTextFull": "Among the many phrases which have been doing double. or even triple, duty lately there is one very well known in modern politics\u2014\"over-all planning.\" I think that it is very often used rather vaguely, but if there was an occasion for over-all planning, this is surely it. The answer to the hon. Member for Lady- <span id=\"1489\" class=\"column-number\" data-column-number=\"1489\"></span> wood (Mr. Yates) is that what are now required are not so much detailed controls, but an over-all international plan for the production and allocation of vital raw materials.<p></p> Now, this situation arises from the present state of the world. Yesterday we had a debate on that situation. Some of us, myself included, do not feel that we should consider ourselves in a state of war with Russia. Many of us do not feel that rearmament alone will guarantee peace. But whatever our views on foreign affairs, we must realise, as a Member of the United Nations, that at the moment we are at war in Korea and in China, and the whole situation we are debating today flows from the fact of war or the threat of war. Those of us who may disagree on foreign policy can be agreed on the very great urgency of ensuring for this country adequate materials for rearmament, and ensuring th

======================================================================
SECURITY
======================================================================
Python type: dict
Top-level keys: ['SearchTerms', 'SpokenResultCount', 'WrittenResultCount', 'CorrectionsResultCount', 'DivisionsResultCount', 'Results', 'TotalResultCount']
SearchTerms: list with 1 items
SpokenResultCount: 0
WrittenResultCount: 0
CorrectionsResultCount: 0
DivisionsResultCount: 0
Results: list with 100 items
TotalResultCount: 3632

Preview:
{
  "SearchTerms": [
    "security"
  ],
  "SpokenResultCount": 0,
  "WrittenResultCount": 0,
  "CorrectionsResultCount": 0,
  "DivisionsResultCount": 0,
  "Results": [
    {
      "MemberName": "",
      "MemberId": -1,
      "AttributedTo": "Mr. Oliver Lyttelton  (Aldershot)",
      "ItemId": 9080417,
      "ContributionExtId": "4983ea2f-6fc8-4f25-9782-085ff79492d7",
      "ContributionText": "I entirely agree with many of the remarks made by the hon. Member for Itchen (Mr. Morley). We do require a new industry in England in oil refining to save dollars. The hon. Member dealt with some cogency with some of the arguments advanced against the s",
      "ContributionTextFull": "I entirely agree with many of the remarks made by the hon. Member for Itchen (Mr. Morley). We do require a new industry in England in oil refining to save dollars. The hon. Member dealt with some cogency with some of the arguments advanced against the siting of this particular refinery at Southampton, but it seemed to me, that he dealt in the most summary and lighthearted way with the defence argument, which to my mind is a decisive matter.<p></p> I remember how in the war I was once asked by the Ministry of Supply to provide 500 Italian prisoners for work at Scunthorpe\u2014I think it was Scunthorpe\u2014and I found them, but there was nowhere for them to live. So I arranged for camp to be built for them. The Ministry of Supply said that the security officers had not been consulted on the matter. I said that they would be consulted at once, and when they were consulted, they said, \"This camp cannot be built there for strategic reasons.\" I asked, \"What strategic reasons?\" These turned out to be that it was too near an important point of production\u2014in fact, the very place where the Italian prisoners were required to work. That is carrying security much too far.<p></p> Could there be greater folly than to site more than half, I think very nearly two-thirds, of the total oil-refining capacity of the country in an area of about one square mile? That is really a decisive point. Everybody connected with Southampton would like to see employment there diversified. I do not wish to go into any other argument in this short intervention except to say that we should require a great deal of convincing that it is a sound plan to site nearly two-thirds\u2014I have heard an even higher figure mentioned\u2014of the oil-refining capacity of the country in a very vulnerable area of a square mile. That is the point on which we shall have to receive a great deal of reassurance from the Minister.",
      "HRSTag": null,
      "HansardSection": null,
      "Timecode": null,
      "DebateSection": "Oil Refinery, The Solent",
      "DebateSectionId": 3069976,
      "DebateSectionExtId": "c0636361-82cc-45fd-8cb1-3100ab4cd8be",
      "SittingDate": "1950-12-15T00:00:00",
      "Section": "Commons Chamber",
      "House": "Commons",
      "OrderInDebateSection": 28,
      "DebateSectionOrder": 10,
      "Rank": 38
    },
    {
      "MemberName": "",
      "MemberId": -1,
      "AttributedTo": "Mr. Paton",
      "ItemId": 9079830,
      "ContributionExtId": "5a315bc3-9e82-440e-856a-9d1bfb4d5882",
      "ContributionText": "I am sorry, but I cannot give way. There is one thing that we are all agreed upon, I am very thankful to say, and that is the agreement that extends far beyond this House, and, I think, reaches to every part of this country and the whole of western Euro",
      "ContributionTextFull": "I am sorry, but I cannot give way.<p></p> There is one thing that we are all agreed upon, I am very thankful to say, and that is the agreement that extends far beyond this House, and, I think, reaches to every part of this country and the whole of western Europe. That is the agreement that none of us wants war with China, and that all of us will do everything possible to try to avoid it. That is something that, to me, is extraordinarily heartening, and I want, therefore, to see the proposal that has been made in Washington for a \"cease fire\" being accepted, and a cessation of these hostilities in Korea that we are all watching with such great anxiety, in order that there might come\u2014what must come eventually, in any case\u2014the opportunity for opening negotiations with China with a view to trying to secure a negotiated settlement and the restoration of peace in that area.<p></p> I was extremely glad this afternoon to hear the Prime Minister say that in any contacts we might make in negotiating with the Chinese, we would be in the position of recognising them as full equals with us and the Western nations in the negotiations; that there would be no attempt whatever to try to talk to the Chinese as if they were, in some way, still in a subordinate position. I am very glad that my right hon. Friend made that statement, because it seems to me there is still far too great a, tendency by hon. Members in this House and by people outside to talk as if t

In [39]:
def find_result_list(data):

    preferred_keys = [
        "Results",
        "results",
        "Items",
        "items",
        "Contributions",
        "contributions"
    ]

    for key in preferred_keys:

        if (
            isinstance(data, dict)
            and key in data
            and isinstance(data[key], list)
        ):
            return key, data[key]

    if isinstance(data, dict):

        for key, value in data.items():

            if isinstance(value, list):
                return key, value

    return None, []


for word, data in test_searches.items():

    key, rows = find_result_list(
        data
    )

    print(
        f"\n{word}: "
        f"result key={key}, "
        f"rows={len(rows)}"
    )

    if rows:

        df = pd.json_normalize(
            rows
        )

        print(
            "Columns:"
        )

        print(
            df.columns.tolist()
        )

        display(
            df.head()
        )

war: result key=Results, rows=100
Columns:
['MemberName', 'MemberId', 'AttributedTo', 'ItemId', 'ContributionExtId', 'ContributionText', 'ContributionTextFull', 'HRSTag', 'HansardSection', 'Timecode', 'DebateSection', 'DebateSectionId', 'DebateSectionExtId', 'SittingDate', 'Section', 'House', 'OrderInDebateSection', 'DebateSectionOrder', 'Rank']

,MemberName,MemberId,AttributedTo,ItemId,ContributionExtId,ContributionText,ContributionTextFull,HRSTag,HansardSection,Timecode,DebateSection,DebateSectionId,DebateSectionExtId,SittingDate,Section,House,OrderInDebateSection,DebateSectionOrder,Rank
0,,-1.0,Sir G. Jeffreys,9080427,c95fec24-1a1d-466c-8474-bb8e0f7421ac,The best way to preserve peace is to be prepar...,The best way to preserve peace is to be prepar...,None,None,None,"Oil Refinery, The Solent",3069976,c0636361-82cc-45fd-8cb1-3100ab4cd8be,1950-12-15T00:00:00,Commons Chamber,Commons,40,10,96
1,,-1.0,Mr. Grimond (Orkney and Shetland),9080077,4740ad57-084e-4eaa-8b5d-8c82973c37ea,Among the many phrases which have been doing d...,Among the many phrases which have been doing d...,None,None,None,Raw Material Supplies,3069857,37aa6fa9-7fb3-418d-8165-b4192ee9e59e,1950-12-15T00:00:00,Commons Chamber,Commons,38,6,96
2,,-1.0,Mr. Chetwynd,9080091,c7035397-dafa-4274-8963-4ef58da90c95,"No, I think it would be far more just to say t...","No, I think it would be far more just to say t...",None,None,None,Raw Material Supplies,3069857,37aa6fa9-7fb3-418d-8165-b4192ee9e59e,1950-12-15T00:00:00,Commons Chamber,Commons,46,6,80
3,,-1.0,Sir G. Jeffreys,9080424,19156fa2-9f87-411f-91cf-93cd5f1aabc9,Is the hon. Gentleman aware that the port of S...,Is the hon. Gentleman aware that the port of S...,None,None,None,"Oil Refinery, The Solent",3069976,c0636361-82cc-45fd-8cb1-3100ab4cd8be,1950-12-15T00:00:00,Commons Chamber,Commons,36,10,64
4,,-1.0,Mr. Oliver Lyttelton (Aldershot),9080047,c763facd-d6af-49cc-970c-debe4548a5bc,Perhaps I can help the hon. Gentleman in the d...,Perhaps I can help the hon. Gentleman in the d...,None,None,None,Raw Material Supplies,3069857,37aa6fa9-7fb3-418d-8165-b4192ee9e59e,1950-12-15T00:00:00,Commons Chamber,Commons,18,6,64

peace: result key=Results, rows=100
Columns:
['MemberName', 'MemberId', 'AttributedTo', 'ItemId', 'ContributionExtId', 'ContributionText', 'ContributionTextFull', 'HRSTag', 'HansardSection', 'Timecode', 'DebateSection', 'DebateSectionId', 'DebateSectionExtId', 'SittingDate', 'Section', 'House', 'OrderInDebateSection', 'DebateSectionOrder', 'Rank']

,MemberName,MemberId,AttributedTo,ItemId,ContributionExtId,ContributionText,ContributionTextFull,HRSTag,HansardSection,Timecode,DebateSection,DebateSectionId,DebateSectionExtId,SittingDate,Section,House,OrderInDebateSection,DebateSectionOrder,Rank
0,,-1,Sir G. Jeffreys,9080427,c95fec24-1a1d-466c-8474-bb8e0f7421ac,The best way to preserve peace is to be prepar...,The best way to preserve peace is to be prepar...,None,None,None,"Oil Refinery, The Solent",3069976,c0636361-82cc-45fd-8cb1-3100ab4cd8be,1950-12-15T00:00:00,Commons Chamber,Commons,40,10,128
1,,-1,Mr. Lindgren,9080429,1f06d899-090b-4d5a-9602-15a6025af9a7,"I am not arguing on that basis, but if war com...","I am not arguing on that basis, but if war com...",None,None,None,"Oil Refinery, The Solent",3069976,c0636361-82cc-45fd-8cb1-3100ab4cd8be,1950-12-15T00:00:00,Commons Chamber,Commons,42,10,85
2,,-1,Mr. Lindgren,9080426,a1a8bd59-6f13-4ac3-81d7-5aee8472547e,The hon. and gallant Gentleman must remember t...,The hon. and gallant Gentleman must remember t...,None,None,None,"Oil Refinery, The Solent",3069976,c0636361-82cc-45fd-8cb1-3100ab4cd8be,1950-12-15T00:00:00,Commons Chamber,Commons,38,10,64
3,,-1,Mr. Grimond (Orkney and Shetland),9080077,4740ad57-084e-4eaa-8b5d-8c82973c37ea,Among the many phrases which have been doing d...,Among the many phrases which have been doing d...,None,None,None,Raw Material Supplies,3069857,37aa6fa9-7fb3-418d-8165-b4192ee9e59e,1950-12-15T00:00:00,Commons Chamber,Commons,38,6,48
4,,-1,Mr. Oliver Lyttelton (Aldershot),9080047,c763facd-d6af-49cc-970c-debe4548a5bc,Perhaps I can help the hon. Gentleman in the d...,Perhaps I can help the hon. Gentleman in the d...,None,None,None,Raw Material Supplies,3069857,37aa6fa9-7fb3-418d-8165-b4192ee9e59e,1950-12-15T00:00:00,Commons Chamber,Commons,18,6,42

security: result key=Results, rows=100
Columns:
['MemberName', 'MemberId', 'AttributedTo', 'ItemId', 'ContributionExtId', 'ContributionText', 'ContributionTextFull', 'HRSTag', 'HansardSection', 'Timecode', 'DebateSection', 'DebateSectionId', 'DebateSectionExtId', 'SittingDate', 'Section', 'House', 'OrderInDebateSection', 'DebateSectionOrder', 'Rank']

,MemberName,MemberId,AttributedTo,ItemId,ContributionExtId,ContributionText,ContributionTextFull,HRSTag,HansardSection,Timecode,DebateSection,DebateSectionId,DebateSectionExtId,SittingDate,Section,House,OrderInDebateSection,DebateSectionOrder,Rank
0,,-1,Mr. Oliver Lyttelton (Aldershot),9080417,4983ea2f-6fc8-4f25-9782-085ff79492d7,I entirely agree with many of the remarks made...,I entirely agree with many of the remarks made...,None,None,None,"Oil Refinery, The Solent",3069976,c0636361-82cc-45fd-8cb1-3100ab4cd8be,1950-12-15T00:00:00,Commons Chamber,Commons,28,10,38
1,,-1,Mr. Paton,9079830,5a315bc3-9e82-440e-856a-9d1bfb4d5882,"I am sorry, but I cannot give way. There is on...","I am sorry, but I cannot give way.<p></p> Ther...",None,None,None,Prime Minister's Visit To Usa,3069686,1f8b6bd6-f5fd-423b-9316-fa46bfd30969,1950-12-14T00:00:00,Commons Chamber,Commons,252,48,64
2,,-1,Mr. Davies,9079090,d064a1dc-8cd3-4e58-99be-c5ba581b5721,"Does the Home Secretary suggest that, tiresome...","Does the Home Secretary suggest that, tiresome...",None,None,None,Interrogation,3069576,b0e69302-7896-4472-ab55-225293e12fab,1950-12-14T00:00:00,Commons Chamber,Commons,11,27,48
3,,-1,Mr. Molson (The High Peak),9079621,5d783a3e-995f-4fe8-b76c-a5566d57f4c9,May I ask the right hon. and learned Gentleman...,May I ask the right hon. and learned Gentleman...,None,None,None,Prime Minister's Visit To Usa,3069686,1f8b6bd6-f5fd-423b-9316-fa46bfd30969,1950-12-14T00:00:00,Commons Chamber,Commons,114,48,32
4,,-1,Mr. Janner,9079432,1ea54598-a4de-49cc-843e-3b8bf211a35a,In view of the very considerable anxiety that ...,In view of the very considerable anxiety that ...,None,None,None,Business Of The House,3069671,bc06f779-b97d-44f3-84aa-68ba5f13978b,1950-12-14T00:00:00,Commons Chamber,Commons,20,43,32

In [40]:
house_tests = {}

for house in [
    "Commons",
    "Lords"
]:

    house_tests[house] = {}

    for word in TARGET_WORDS:

        house_tests[house][word] = (
            search_spoken_contributions(
                term=word,
                start_date=TEST_START,
                end_date=TEST_END,
                house=house,
                take=20
            )
        )

        time.sleep(1)

Attempt 1: 500
{"Message":"An error has occurred."}

In [41]:
def get_historic_sitting_days(
    start_date,
    end_date,
    house="Commons",
    skip=0,
    take=100
):

    url = (
        f"{API_BASE}/"
        "historicsittingdays"
    )

    params = {
        "queryParams.house":
            house,
        "queryParams.startDate":
            start_date,
        "queryParams.endDate":
            end_date,
        "queryParams.skip":
            skip,
        "queryParams.take":
            take,
        "queryParams.orderBy":
            "SittingDateAsc",
        "queryParams.hasSittingSections":
            True
    }

    response = session.get(
        url,
        params=params,
        timeout=60
    )

    print(
        "Status:",
        response.status_code
    )

    print(
        "URL:",
        response.url
    )

    if response.status_code != 200:
        print(
            response.text[:3000]
        )

    response.raise_for_status()

    return response.json()


sitting_test = (
    get_historic_sitting_days(
        "1949-05-01",
        "1949-05-07",
        house="Commons"
    )
)

print(
    json.dumps(
        sitting_test,
        indent=2
    )[:10000]
)

Status: 200
URL: https://hansard-api.parliament.uk/historicsittingdays?queryParams.house=Commons&queryParams.startDate=1949-05-01&queryParams.endDate=1949-05-07&queryParams.skip=0&queryParams.take=100&queryParams.orderBy=SittingDateAsc&queryParams.hasSittingSections=True
{
  "Item": {
    "Results": [
      {
        "HouseId": 1,
        "SittingDate": "1949-05-02T00:00:00"
      },
      {
        "HouseId": 1,
        "SittingDate": "1949-05-03T00:00:00"
      },
      {
        "HouseId": 1,
        "SittingDate": "1949-05-04T00:00:00"
      },
      {
        "HouseId": 1,
        "SittingDate": "1949-05-05T00:00:00"
      },
      {
        "HouseId": 1,
        "SittingDate": "1949-05-06T00:00:00"
      }
    ],
    "TotalResultCount": 5
  },
  "Success": true,
  "Errors": []
}

In [42]:
def search_member(
    name,
    date=None,
    house="Commons"
):
    url = f"{API_BASE}/search/members.json"

    params = {
        "queryParameters.searchTerm": name,
        "queryParameters.house": house,
        "queryParameters.includeFormer": True,
        "queryParameters.includeCurrent": True,
        "queryParameters.skip": 0,
        "queryParameters.take": 20,
    }

    if date is not None:
        params["queryParameters.date"] = date

    response = session.get(
        url,
        params=params,
        timeout=30
    )

    print("Status:", response.status_code)
    print("URL:", response.url)

    if response.status_code != 200:
        print(response.text[:3000])

    response.raise_for_status()

    return response.json()

member_test = search_member(
    name="Sir J. Grigg",
    date="1945-01-16",
    house="Commons"
)


print(
    json.dumps(
        member_test,
        indent=2
    )[:10000]
)

def find_member_rows(data):
    if not isinstance(data, dict):
        return []

    for key in [
        "Members",
        "Results",
        "Items"
    ]:
        if (
            key in data
            and isinstance(data[key], list)
        ):
            return data[key]

    for value in data.values():
        if isinstance(value, list):
            return value

    return []


member_rows = find_member_rows(
    member_test
)

print(
    "Member rows:",
    len(member_rows)
)

if member_rows:

    member_df = pd.json_normalize(
        member_rows
    )

    print(member_df.columns.tolist())

    display(member_df)

Status: 200
URL: https://hansard-api.parliament.uk/search/members.json?queryParameters.searchTerm=Sir+J.+Grigg&queryParameters.house=Commons&queryParameters.includeFormer=True&queryParameters.includeCurrent=True&queryParameters.skip=0&queryParameters.take=20&queryParameters.date=1945-01-16
{
  "Results": [],
  "TotalResultCount": 0
}
Member rows: 0

In [43]:
security_df = pd.json_normalize(
    test_searches["security"]["Results"]
)

display(
    security_df[
        [
            "AttributedTo",
            "MemberId",
            "SittingDate",
            "DebateSection",
            "ContributionTextFull"
        ]
    ].head(10)
)

,AttributedTo,MemberId,SittingDate,DebateSection,ContributionTextFull
0,Mr. Oliver Lyttelton (Aldershot),-1,1950-12-15T00:00:00,"Oil Refinery, The Solent",I entirely agree with many of the remarks made...
1,Mr. Paton,-1,1950-12-14T00:00:00,Prime Minister's Visit To Usa,"I am sorry, but I cannot give way.<p></p> Ther..."
2,Mr. Davies,-1,1950-12-14T00:00:00,Interrogation,"Does the Home Secretary suggest that, tiresome..."
3,Mr. Molson (The High Peak),-1,1950-12-14T00:00:00,Prime Minister's Visit To Usa,May I ask the right hon. and learned Gentleman...
4,Mr. Janner,-1,1950-12-14T00:00:00,Business Of The House,In view of the very considerable anxiety that ...
5,Mr. Ede,-1,1950-12-14T00:00:00,Soviet Trade Union Delegation (Visas),"Before these visas were granted, I took the pr..."
6,Mr. Ede,-1,1950-12-14T00:00:00,Interrogation,In many foreign countries which have a land fr...
7,Mr. Eden,-1,1950-12-14T00:00:00,Prime Minister's Visit To Usa,"All right, but if we have a finger in every pi..."
8,"Mr. Julian Amery (Preston, North)",-1,1950-12-14T00:00:00,Prime Minister's Visit To Usa,The hon. Member for Leek (Mr. Harold Davies) a...
9,Mr. Walker-Smith,-1,1950-12-14T00:00:00,Prime Minister's Visit To Usa,"I hate to refuse to give way, but there is not..."

In [44]:
speaker_text = (
    security_df
    .iloc[0]["AttributedTo"]
)

speaker_date = (
    security_df
    .iloc[0]["SittingDate"][:10]
)

print(
    "Speaker:",
    speaker_text
)

print(
    "Date:",
    speaker_date
)

Speaker: Mr. Oliver Lyttelton  (Aldershot)
Date: 1950-12-15

In [ ]:
later_test = search_spoken_contributions(
    term="security",
    start_date="1975-01-01",
    end_date="1975-01-31",
    house="Commons",
    take=50
)

if later_test is not None:

    later_df = pd.json_normalize(
        later_test.get(
            "Results",
            []
        )
    )

    if len(later_df) > 0:

        display(
            later_df[
                [
                    "MemberName",
                    "MemberId",
                    "AttributedTo",
                    "SittingDate",
                    "DebateSection"
                ]
            ].head(20)
        )

    else:
        print("No results returned.")

else:
    print("API request failed.")

display(
    later_df[
        [
            "MemberName",
            "MemberId",
            "AttributedTo",
            "SittingDate",
            "DebateSection"
        ]
    ].head(20)
)

Attempt 1: 500
{"Message":"An error has occurred."}

KeyError: 'Results'

In [ ]:
print(
    "Rows:",
    len(later_df)
)

print(
    "Valid MemberId:",
    (
        later_df["MemberId"]
        .fillna(-1)
        .ne(-1)
        .sum()
    )
)

print(
    "Valid MemberId %:",
    round(
        (
            later_df["MemberId"]
            .fillna(-1)
            .ne(-1)
            .mean()
            * 100
        ),
        1
    )
)

Rows: 100
Valid MemberId: 0
Valid MemberId %: 0.0

In [ ]:
TEST_PERIODS = [
    ("1905", "1905-01-01", "1905-01-31"),
    ("1925", "1925-01-01", "1925-01-31"),
    ("1945", "1945-01-01", "1945-01-31"),
    ("1965", "1965-01-01", "1965-01-31"),
    ("1985", "1985-01-01", "1985-01-31"),
    ("2000", "2000-01-01", "2000-01-31"),
]

audit_rows = []

for label, start_date, end_date in TEST_PERIODS:

    result = search_spoken_contributions(
        term="security",
        start_date=start_date,
        end_date=end_date,
        house="Commons",
        take=50
    )

    if result is None:
        audit_rows.append({
            "year": label,
            "status": "failed"
        })
        continue

    rows = result.get("Results", [])

    if not rows:
        audit_rows.append({
            "year": label,
            "status": "no results"
        })
        continue

    df = pd.json_normalize(rows)

    audit_rows.append({
        "year": label,
        "status": "ok",
        "rows_returned": len(df),
        "total_results":
            result.get("TotalResultCount"),
        "valid_member_id_pct":
            df["MemberId"]
            .fillna(-1)
            .ne(-1)
            .mean() * 100,
        "speaker_label_pct":
            df["AttributedTo"]
            .fillna("")
            .str.strip()
            .ne("")
            .mean() * 100,
        "debate_title_pct":
            df["DebateSection"]
            .fillna("")
            .str.strip()
            .ne("")
            .mean() * 100
    })

    time.sleep(1)

audit_df = pd.DataFrame(audit_rows)

display(audit_df)

security / Commons -> 200
security / Commons -> 200
security / Commons -> 500
{"Message":"An error has occurred."}

HTTPError: 500 Server Error: Internal Server Error for url: https://hansard-api.parliament.uk/search/contributions/Spoken.json?queryParameters.house=Commons&queryParameters.startDate=1945-01-01&queryParameters.endDate=1945-12-31&queryParameters.searchTerm=security&queryParameters.skip=0&queryParameters.take=100&queryParameters.orderBy=SittingDateAsc

In [ ]:
def test_member_names(
    names,
    date=None,
    house="Commons"
):
    results = {}

    for name in names:

        data = search_member(
            name=name,
            date=date,
            house=house
        )

        results[name] = data

        print(
            "\n",
            "=" * 60,
            "\n",
            name
        )

        print(
            json.dumps(
                data,
                indent=2
            )[:3000]
        )

        time.sleep(0.5)

    return results


member_name_tests = test_member_names(
    [
        "Grigg",
        "Strauss",
        "Bevin"
    ],
    date="1945-01-16",
    house="Commons"
)

In [ ]:
TEST_DEBATE_ID = (
    test_searches[
        "security"
    ]["Results"][0][
        "DebateSectionExtId"
    ]
)

url = (
    f"{API_BASE}/debates/"
    f"speakerslist/"
    f"{TEST_DEBATE_ID}.json"
)

response = session.get(
    url,
    timeout=30
)

print(
    "Status:",
    response.status_code
)

print(
    response.text[:5000]
)